### ISSUE TITLE
I want to ask you about how to configure the file structure ?

### ISSUE THREAD

**Issue by Leo-lin214** [sean-hill/ionic-user-auth-express#1]

**Comment by sean-hill** [comment]
Check out the file structure of this repo, that is how I have configured it as an example. If this doesn't help, please provide more detail with your question. Thanks!

**Comment by Leo-lin214** [comment]
For ionic, you can start "ionic start mobile", and for express , you can start "express server". So how do you combine two of them together?

**Comment by sean-hill** [comment]
What I do is after starting a new ionic project with `ionic start mobile` and starting a new express project, I have two tabs open in my terminal, one for the mobile app, one for the express server. Then I run `ionic serve` in the mobile app tab, and `node app.js` for the express server one.
